<?php

/**
 * @file
 * Don't display feedback when adding new query.
 */
 
 /**
 * Implementation of hook_form_alter().
 */
function dilatoit_query_extra_form_alter(&$form, &$form_state, $form_id) {
  $arg_first = arg(0);
  $arg_second = arg(1);
  $arg_third = arg(2);
  if ($arg_first == 'node' && $arg_second == 'add' && $arg_third == 'query') {
    $array_feedback = $form['field_query_feedback'];
    $array_feedback['#type'] = 'hidden';
    $form['field_query_feedback'] = $array_feedback;
  } 
}