<?php
/**
 * @file Create project id like "Project – 客户名 + 年份 + ID".
 *
 *
 */

 /**
 * Implementation of hook_nodeapi().
 */
function dilatoit_create_project_id_nodeapi(&$node, $op, $a3 = NULL, $a4 = NULL) {
  switch ($op) {
    case 'insert':
      if ($node->type =='project') {
        $query = db_query("SELECT field_project_client_uid AS uid , field_duration_value AS date FROM {content_type_project} WHERE nid = %d", $node->nid);
        if ($result = db_fetch_array($query)) {
          $user = user_load($result['uid']);
          $client_name = $user->name;
          $date = $result['date'];
          $date = substr($date, 0, 4);
          $project_id = $client_name . '-' . $date . '-' . $node->nid;
          db_query("UPDATE {content_type_project} SET field_project_project_id_value = '%s' WHERE nid = %d", $project_id, $node->nid);
        }
      }
    break;
  }
}









